version: "3.8"
services:
  rq:
    build: .
    command: make run.rqworker
    env_file: ./.env.local
    depends_on:
      - redis
  bot:
    build: .
    command: make run.bot
    ports:
      - 8001:8001
    env_file: ./.env.local
    depends_on:
      - backend
  backend:
    build: .
    command: make collectstatic migrate run.server.local
    ports:
      - 8000:8000
    env_file: ./.env.local
    environment:
      - DJANGO_SETTINGS_MODULE=admission.settings.local
    depends_on:
      - redis
      - pgdb
  pgdb:
    image: postgres:latest
    env_file: ./.env.local
    container_name: pgdb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - "cache:/data"

volumes:
  pgdbdata: null
  cache:
    driver: local
