version: "3.8"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file: ./.env.production
    depends_on:
      - redis
      - pgdb
  pgdb:
    image: postgres:latest
    env_file: ./.env.production
    container_name: pgdb
    expose:
      - 5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    volumes:
      - "cache:/data"

volumes:
  pgdbdata: null
  cache:
    driver: local
