# Generated by Django 5.0.4 on 2024-06-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
