# Generated by Django 5.0.4 on 2024-06-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_helptheme_alter_helprequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='theme',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='helper.helptheme'),
            preserve_default=False,
        ),
    ]
