# Generated by Django 5.0 on 2024-04-10 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='purpose',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='peopleQueue.talonpurposes'),
            preserve_default=False,
        ),
    ]
