# Generated by Django 5.0 on 2024-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0003_talonlog_add_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talonlog',
            name='add_json',
        ),
    ]
