# Generated by Django 5.0 on 2024-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0004_remove_talonlog_add_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talonlog',
            name='action',
            field=models.CharField(choices=[('Created', 'Создан'), ('Started', 'Запущен'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен'), ('Redirected', 'Перенаправлен')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TalonAction',
        ),
    ]
