# Generated by Django 5.0.4 on 2024-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0007_talonlog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talonlog',
            name='action',
            field=models.CharField(choices=[('Created', 'Создан'), ('Assigned', 'Назначен'), ('Started', 'Запущен'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен'), ('Redirected', 'Перенаправлен')], max_length=20),
        ),
    ]
