# Generated by Django 5.0.4 on 2024-05-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0008_alter_talonlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='compliting',
            field=models.BooleanField(default=False),
        ),
    ]
