# Generated by Django 5.0.4 on 2024-05-17 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0009_talon_compliting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsettings',
            name='automatic_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OperatorQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peopleQueue.talonpurposes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_queue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
