# Generated by Django 5.0.4 on 2024-05-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0010_operatorsettings_automatic_assignment_operatorqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorqueue',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peopleQueue.talonpurposes'),
        ),
    ]
