# Generated by Django 5.0.4 on 2024-05-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0012_alter_operatorqueue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='tg_chat_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
