# Generated by Django 5.0.4 on 2024-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0014_operatorlocation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
