# Generated by Django 5.0.4 on 2024-06-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0015_talon_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsettings',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='operator_settings', to='peopleQueue.talonpurposes'),
        ),
    ]
