# Generated by Django 5.0.4 on 2024-07-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0016_alter_operatorsettings_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='action',
            field=models.CharField(choices=[('Created', 'Создан'), ('Assigned', 'Назначен'), ('Started', 'Запущен'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен'), ('Redirected', 'Перенаправлен')], default='Created', max_length=20),
        ),
    ]
