# Generated by Django 5.0.4 on 2026-06-10 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleQueue', '0018_talon_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalonMessengerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('external_user_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_subscriptions', to='peopleQueue.talon')),
            ],
        ),
    ]
